language: node_js
node_js:
- '8'

jobs:
  include:
    - stage: deploy
      install:
      - ./install.sh
      - npm i -g @hkube/hkube
      script: ./deploy.sh
    - stage: test
      install:
      - ./install.sh
      - npm i -g npm@6
      script: ./test.sh
      sudo: required
    - stage: test-short
      install:
      - ./install.sh
      - npm i -g npm@6
      script: ./test-short.sh
stages:
  - deploy
  - test-short
  - test
    if: tag IS present
    
  