language: node_js
node_js:
- '8'
install:
  - ./install.sh
  - npm i -g @hkube/hkube
jobs:
  include:
    - stage: deploy
      script: ./deploy.sh
    - stage: test
      script: ./test.sh
stages:
  - deploy
  - test
  