language: node_js
node_js:
- '8'

jobs:
  include:
    - stage: deploy
      install:
      - ./install.sh
      - npm i -g @hkube/hkube
      script: ./deploy.sh
    - stage: test
      install:
      - ./install.sh
      script: ./test.sh
      sudo: required
stages:
  - deploy
  - test
  