language: node_js
node_js:
- '10'

jobs:
  include:
    - stage: deploy
      install:
      - ./install.sh
      script: ./deploy.sh
    - stage: test
      install:
      - ./install.sh
      - npm i -g npm@6
      script: ./test.sh
      sudo: required
    - stage: test-short
      install:
      - ./install.sh
      - npm i -g npm@6
      script: ./test-short.sh || true
stages:
  - deploy
  - test-short
  - name: test
    # if: tag IS present
    
  
